/* AERONAV Family Call RC10.14 — bidirectional LiveKit voice call helper.
   Uses the existing Railway token server with call-pilot / call-family roles.
   The signaling (ring/accept/decline/end) is handled by the Family Air / Viewer pages via Supabase. */
(()=>{
'use strict';
const VERSION='RC10.22-family-call';
const SDK_VERSION='2.22.3';
const SDK_URL=`https://cdn.jsdelivr.net/npm/livekit-client@${SDK_VERSION}/dist/livekit-client.umd.min.js`;
const DEFAULT_TOKEN_SERVER='https://aeronav-cockpit-token-server-production.up.railway.app';
const LS_ENDPOINT='aeronav.cockpit.tokenServer';
const SS_PILOT='aeronav.cockpit.pilotCode';
const SS_FAMILY='aeronav.mathia.familyCode';
const LS_DEVICE_TOKEN='aeronav.mathia.deviceToken';
const STYLE_ID='aeronav-family-call-style';
let sdkPromise=null;
const sessions=new Map();
function injectStyle(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
.afc{margin-top:10px;padding:12px;border:1px solid #285974;border-radius:14px;background:#061925;color:#eef7ff}.afc-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.afc-sub{font-size:11px;color:#93adbe;line-height:1.45;margin-top:3px}.afc-pill{font-size:9px;font-weight:900;padding:5px 7px;border-radius:999px;background:#4a3412;color:#ffdc8c}.afc-pill.ok{background:#103f37;color:#91f3d5}.afc-pill.bad{background:#3a2530;color:#ffb5cd}.afc-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.afc-btn{border:1px solid #285974;background:#10344a;color:#dff7ff;border-radius:10px;padding:9px 11px;font-weight:800}.afc-btn.primary{border:0;background:linear-gradient(135deg,#2fd1ff,#168bb7);color:#031720}.afc-field{margin-top:10px}.afc-field label{font-size:9px;color:#87a9ba;font-weight:900}.afc-field input{width:100%;margin-top:4px;background:#07131c;border:1px solid #20495e;color:#eaf8ff;border-radius:9px;padding:9px}.afc-audio audio{display:none}`;document.head.appendChild(s)}
function endpoint(){return (localStorage.getItem(LS_ENDPOINT)||DEFAULT_TOKEN_SERVER).replace(/\/$/,'')}
function safe(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function fetchJson(url,init={},timeout=12000){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{...init,signal:ctl.signal});let j={};try{j=await r.json()}catch(_){}return{r,j}}finally{clearTimeout(t)}}
function loadSdk(){if(window.LivekitClient)return Promise.resolve(window.LivekitClient);if(sdkPromise)return sdkPromise;sdkPromise=new Promise((resolve,reject)=>{const existing=[...document.scripts].find(x=>x.src===SDK_URL);const done=()=>window.LivekitClient?resolve(window.LivekitClient):reject(new Error('LiveKit indisponível.'));if(existing){existing.addEventListener('load',done,{once:true});existing.addEventListener('error',()=>reject(new Error('Falha ao carregar LiveKit.')),{once:true});return}const sc=document.createElement('script');sc.src=SDK_URL;sc.async=true;sc.crossOrigin='anonymous';sc.onload=done;sc.onerror=()=>reject(new Error('Falha ao carregar LiveKit.'));document.head.appendChild(sc)});return sdkPromise}
async function getToken(role,code,callId){const familySide=role==='family'||role==='call-family',deviceToken=familySide?(localStorage.getItem(LS_DEVICE_TOKEN)||''):'';if(!code&&!deviceToken)throw new Error('Ligação Family não configurada.');const headers={'Content-Type':'application/json'};if(code)headers['X-AeroNav-Code']=code;if(deviceToken)headers['X-AeroNav-Device-Token']=deviceToken;const {r,j}=await fetchJson(endpoint()+'/token',{method:'POST',cache:'no-store',credentials:'omit',headers,body:JSON.stringify({role,call_id:callId})});if(!r.ok)throw new Error(j?.error||`Token server HTTP ${r.status}`);if(!j?.server_url||!j?.participant_token)throw new Error('Resposta de chamada incompleta.');return j}
class FamilyCallSession{
 constructor(side){this.side=side;this.room=null;this.connected=false;this.muted=false;this.callId='';this.host=null;this.trackEls=new Map();this.onLocalHangup=null;}
 mount(host){injectStyle();this.host=typeof host==='string'?document.querySelector(host):host;if(!this.host)return this;const key=this.side==='pilot'?SS_PILOT:SS_FAMILY;const autoFamily=this.side==='family'?(localStorage.getItem('aeronav.mathia.viewer.key')||''):'';const code=safe(sessionStorage.getItem(key)||autoFamily||'');const codeField=this.side==='pilot'?`<div class="afc-field"><label>CÓDIGO PILOT<input data-fc-code type="password" value="${code}" autocomplete="off" placeholder="Código Railway"></label></div>`:`<div class="afc-sub" style="margin-top:8px">Código Family carregado automaticamente da ligação familiar.</div>`;this.host.innerHTML=`<div class="afc"><div class="afc-head"><div><strong>📞 Family Call</strong><div class="afc-sub">Chamada de voz privada pela Internet entre AERONAV e Family Viewer.</div></div><span class="afc-pill" data-fc-status>${this.connected?'EM CHAMADA':'PRONTO'}</span></div>${codeField}<div class="afc-actions"><button class="afc-btn" data-fc-mute ${this.connected?'':'disabled'}>${this.muted?'🎙 Ativar microfone':'🔇 Silenciar'}</button><button class="afc-btn" data-fc-speaker ${this.connected?'':'disabled'}>🔊 Ativar áudio</button><button class="afc-btn" data-fc-end ${this.connected?'':'disabled'}>Desligar</button></div><div class="afc-audio" data-fc-audio></div><div class="afc-sub" data-fc-note style="margin-top:9px">A chamada requer Internet em ambos os aparelhos.</div></div>`;this._bind();return this}
 _bind(){if(!this.host)return;this.host.querySelector('[data-fc-mute]')?.addEventListener('click',()=>this.toggleMute());this.host.querySelector('[data-fc-speaker]')?.addEventListener('click',()=>this.resumeAudio());this.host.querySelector('[data-fc-end]')?.addEventListener('click',async()=>{await this.leave();this.onLocalHangup?.()});}
 code(){const inp=this.host?.querySelector('[data-fc-code]');const key=this.side==='pilot'?SS_PILOT:SS_FAMILY;const familyAuto=this.side==='family'?(localStorage.getItem('aeronav.mathia.viewer.key')||''):'';const v=inp?.value?.trim()||sessionStorage.getItem(key)||familyAuto||'';if(v)sessionStorage.setItem(key,v);return v}
 status(text,kind=''){const el=this.host?.querySelector('[data-fc-status]');if(el){el.textContent=text;el.className='afc-pill'+(kind?' '+kind:'')}}
 note(text){const el=this.host?.querySelector('[data-fc-note]');if(el)el.textContent=text}
 async join(callId){if(this.connected&&this.callId===callId){await this.resumeAudio();return true}await this.leave(false);this.callId=callId;this.status('A LIGAR');try{const LK=await loadSdk();const auth=await getToken(this.side==='pilot'?'call-pilot':'call-family',this.code(),callId);const room=new LK.Room({adaptiveStream:true,dynacast:true});this.room=room;const RE=LK.RoomEvent;room.on(RE.TrackSubscribed,track=>{if(track.kind!=='audio')return;const el=track.attach();el.autoplay=true;el.playsInline=true;this.host?.querySelector('[data-fc-audio]')?.appendChild(el);this.trackEls.set(track,el);el.play?.().catch(()=>this.note('Toque em “Ativar áudio” se não ouvir a chamada.'))});room.on(RE.TrackUnsubscribed,track=>{const el=this.trackEls.get(track);try{track.detach(el)}catch(_){}try{el?.remove()}catch(_){}this.trackEls.delete(track)});room.on(RE.Disconnected,()=>{this.connected=false;this.status('DESLIGADO');this._refreshButtons()});await room.connect(auth.server_url,auth.participant_token,{autoSubscribe:true});await room.localParticipant.setMicrophoneEnabled(true,{echoCancellation:true,noiseSuppression:true,autoGainControl:true});this.connected=true;this.muted=false;this.status('EM CHAMADA','ok');this.note('Ligação de voz ativa.');await this.resumeAudio().catch(()=>{});this._refreshButtons();return true}catch(e){this.status('ERRO','bad');this.note(String(e?.message||e));await this.leave(false);throw e}}
 _refreshButtons(){if(!this.host)return;const m=this.host.querySelector('[data-fc-mute]'),s=this.host.querySelector('[data-fc-speaker]'),e=this.host.querySelector('[data-fc-end]');[m,s,e].forEach(x=>{if(x)x.disabled=!this.connected});if(m)m.textContent=this.muted?'🎙 Ativar microfone':'🔇 Silenciar'}
 async toggleMute(){if(!this.room||!this.connected)return;this.muted=!this.muted;await this.room.localParticipant.setMicrophoneEnabled(!this.muted);this._refreshButtons()}
 async resumeAudio(){if(!this.room)return;try{if(typeof this.room.startAudio==='function')await this.room.startAudio();for(const el of this.trackEls.values())await el.play?.();this.note('Áudio ativo.')}catch(e){this.note('Áudio bloqueado pelo sistema. Toque novamente.')};}
 async leave(clearId=true){const r=this.room;this.room=null;this.connected=false;try{if(r?.localParticipant?.isMicrophoneEnabled)await r.localParticipant.setMicrophoneEnabled(false)}catch(_){}try{r?.disconnect()}catch(_){}for(const [t,el] of this.trackEls){try{t.detach(el)}catch(_){}try{el.remove()}catch(_){}}this.trackEls.clear();if(clearId)this.callId='';this.status('PRONTO');this._refreshButtons()}
}
function session(side){if(!sessions.has(side))sessions.set(side,new FamilyCallSession(side));return sessions.get(side)}
window.AERONAVFamilyCall={mountPilot:(sel)=>session('pilot').mount(sel),mountViewer:(sel)=>session('family').mount(sel),pilot:()=>session('pilot'),viewer:()=>session('family'),version:VERSION};
})();
